### ISSUE TITLE
AudioContexts are not being freed.

### ISSUE THREAD

**Issue by naturalethic** [hacklily/hackmidi#1]
Cannot create more than 6 players.  On the 7th this error is thrown:

```
Uncaught (in promise) DOMException: Failed to construct 'AudioContext': The number of hardware contexts provided (6) is greater than or equal to the maximum bound (6).
```

I'm calling `player.destroy` on each one, but it appears that is not freeing the AudioContext.  (It looks like `close` must be called on the context.

**Comment by naturalethic** [comment]
Yep.  Here's the solution:
```
player._node.context.close()
player.destroy()
```

**Comment by jocelyn-stericker** [comment]
Published hackmidi 0.0.3 — thank you for your report.

https://github.com/naturalethic/react-midi-player looks cool!

**Comment by naturalethic** [comment]
Hah, thanks.  It was just a demo written in the course of interviewing for a position.  You know, it took me some digging to find your midi library -- the main one returned from a google search actually includes some malware that mines cryptocoins in the browser of whoever loads it.  I wonder if you might be able to do some SEO or some other action to promote this over that thing.  I dunno.

**Comment by jocelyn-stericker** [comment]
Yes, I mostly made this in anger over that exact project.

If you have any suggestions on how to promote this, let me know — I’m not even sure where to start.
